### ISSUE TITLE
Windows下启动报错

### ISSUE THREAD

**Issue by ShadowZheng** [jianliaoim/talk-os#21]
错误如下：
```bash
info 2016-07-24T21:44:38.428Z Account initialized
ReferenceError: Invalid left-hand side in assignment
  at exports.runInThisContext (vm.js:53:16)
  at Module._compile (module.js:373:25)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (D:\WebStormProjects\talk-os\talk-account\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (D:\WebStormProjects\talk-os\talk-api2x\node_modules\express\lib\router\layer.js:16:18)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (D:\WebStormProjects\talk-os\talk-account\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (D:\WebStormProjects\talk-os\talk-api2x\node_modules\express\lib\router\route.js:18:13)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (D:\WebStormProjects\talk-os\talk-account\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (D:\WebStormProjects\talk-os\talk-api2x\node_modules\express\lib\router\index.js:16:13)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (D:\WebStormProjects\talk-os\talk-account\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (D:\WebStormProjects\talk-os\talk-api2x\node_modules\express\lib\application.js:17:14)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (D:\WebStormProjects\talk-os\talk-account\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (D:\WebStormProjects\talk-os\talk-api2x\node_modules\express\lib\express.js:17:13)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (D:\WebStormProjects\talk-os\talk-account\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
 at require (internal/module.js:12:17)
  at Object.<anonymous> (D:\WebStormProjects\talk-os\talk-api2x\server\server.coffee:1:11)
  at Object.<anonymous> (D:\WebStormProjects\talk-os\talk-api2x\server\server.coffee:1:1)
  at Module._compile (module.js:409:26)
  at Object.loadFile (D:\WebStormProjects\talk-os\talk-account\node_modules\coffee-script\lib\coffee-script\register.js:16:19)
  at Module.load (D:\WebStormProjects\talk-os\talk-account\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (D:\WebStormProjects\talk-os\app.coffee:13:10)
  at Object.<anonymous> (D:\WebStormProjects\talk-os\app.coffee:1:1)
  at Module._compile (module.js:409:26)
  at Object.exports.run (C:\Users\minzh\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\coffee-script.js:134:23)
  at compileScript (C:\Users\minzh\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\command.js:224:29)
  at compilePath (C:\Users\minzh\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\command.js:174:14)
  at Object.exports.run (C:\Users\minzh\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\command.js:98:20)
  at Object.<anonymous> (C:\Users\minzh\AppData\Roaming\npm\node_modules\coffee-script\bin\coffee:7:41)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:968:3
```

在linux和mac上好像没有这个问题，但是windows上确实有，
coffee app.coffee 在第一行就出错了，也不知道是什么问题，
还请麻烦查看一下。

@sailxjx @Boshen

**Comment by sailxjx** [comment]
用 `coffee -c .` 把 coffeescript 转成 js，再用 `node app.js` 试试能不能启动

**Comment by tqcenglish** [comment]
coffee -c .     
talk-os/talk-web/test/spec/util/emoji.spec.coffee:25:1: error: unexpected indentation
        '<img align="absmiddle" alt=":smile:" class="emoji" src="https://dn-talk.oss.aliyuncs.com/icons/emoji/smile.png><img align="absmiddle" alt=":smile:" class="emoji" src="https://dn-talk.oss.aliyuncs.com/icons/emoji/smile.png><img align="absmiddle" alt=":smile:" class="emoji" src="https://dn-talk.oss.aliyuncs.com/icons/emoji/smile.png>'

os: mac
CoffeeScript version 1.10.0

**Comment by sailxjx** [comment]
只编译 talk-api2x 下面的文件

**Comment by tqcenglish** [comment]
现在是正常启动后，注册账号后，一直卡在首页？

**Comment by sailxjx** [comment]
Chrome console 截图发来看一下吧

**Comment by tqcenglish** [comment]
![image](https://cloud.githubusercontent.com/assets/3167619/17540670/7f146be8-5eea-11e6-9b37-4f979486678d.png)

刷新一次后终端显示 
```
info 2016-08-10T03:06:32.280Z Connected 2, disconnected 1, online 1
info 2016-08-10T03:06:52.281Z Connected 2, disconnected 1, online 1
info 2016-08-10T03:07:12.284Z Connected 2, disconnected 1, online 1
```

另外请问是否有办法直接在浏览器调试 talk-web/client 下的代码，不进行 build.

**Comment by sailxjx** [comment]
从截图来是都正常的，单独启动 web 可以进入 talk-web 用 `gulp webpack-dev`，不行就问 @Boshen

**Comment by ShadowZheng** [comment]
coffee -c app.coffee后用node启动还是会报错，然后我把项目重新clone下来重新按照流程搞了一遍，报错如下：
```bash
$ npm start

> talk-os@1.0.0 start D:\WebStormProjects\Bim-Web
> coffee app.coffee

info 2016-08-16T06:15:25.814Z Account initialized
SyntaxError: Invalid regular expression: /^\messages\(?:([^\/]+?))\repost\/?$/: Unmatch                                                         ed ')'
  at new RegExp (native)
  at pathtoRegexp (D:\WebStormProjects\Bim-Web\talk-api2x\node_modules\express\node_mod                                                         ules\path-to-regexp\index.js:128:10)
  at new Layer (D:\WebStormProjects\Bim-Web\talk-api2x\node_modules\express\lib\router\                                                         layer.js:45:17)
  at Function.route (D:\WebStormProjects\Bim-Web\talk-api2x\node_modules\express\lib\ro                                                         uter\index.js:494:15)
  at EventEmitter.app.(anonymous function) (D:\WebStormProjects\Bim-Web\talk-api2x\node                                                         _modules\express\lib\application.js:480:30)
  at EventEmitter.app.(anonymous function) [as post] (D:\WebStormProjects\Bim-Web\talk-                                                         api2x\node_modules\sundae\lib\router.js:148:20)
  at Object.<anonymous> (D:\WebStormProjects\Bim-Web\talk-api2x\server\config\routes.co                                                         ffee:24:5)
  at Object.<anonymous> (D:\WebStormProjects\Bim-Web\talk-api2x\server\config\routes.co                                                         ffee:1:1)
  at Module._compile (module.js:409:26)
  at Object.loadFile (D:\WebStormProjects\Bim-Web\talk-api2x\node_modules\coffee-script                                                         \lib\coffee-script\register.js:16:19)
  at Module.load (D:\WebStormProjects\Bim-Web\talk-api2x\node_modules\coffee-script\lib                                                         \coffee-script\register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (D:\WebStormProjects\Bim-Web\talk-api2x\server\server.coffee:25                                                         :1)
  at Object.<anonymous> (D:\WebStormProjects\Bim-Web\talk-api2x\server\server.coffee:1:                                                         1)
  at Module._compile (module.js:409:26)
  at Object.loadFile (D:\WebStormProjects\Bim-Web\talk-account\node_modules\coffee-scri                                                         pt\lib\coffee-script\register.js:16:19)
  at Module.load (D:\WebStormProjects\Bim-Web\talk-account\node_modules\coffee-script\l                                                         ib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (D:\WebStormProjects\Bim-Web\app.coffee:13:10)
  at Object.<anonymous> (D:\WebStormProjects\Bim-Web\app.coffee:1:1)
  at Module._compile (module.js:409:26)
  at Object.exports.run (D:\WebStormProjects\Bim-Web\node_modules\coffee-script\lib\cof                                                         fee-script\coffee-script.js:134:23)
  at compileScript (D:\WebStormProjects\Bim-Web\node_modules\coffee-script\lib\coffee-s                                                         cript\command.js:224:29)
  at compilePath (D:\WebStormProjects\Bim-Web\node_modules\coffee-script\lib\coffee-scr                                                         ipt\command.js:174:14)
  at Object.exports.run (D:\WebStormProjects\Bim-Web\node_modules\coffee-script\lib\cof                                                         fee-script\command.js:98:20)
  at Object.<anonymous> (D:\WebStormProjects\Bim-Web\node_modules\coffee-script\bin\cof                                                         fee:7:41)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:968:3
```
好像是正则表达式的错误，在ubuntu上没有遇到这样的错啊。
@Boshen 大神，麻烦请帮忙看看，毕竟还是一堆程序猿在用win的啊。

**Comment by Boshen** [comment]
程序猿遇到这种问题不应该是自己解决吗？ 

regex可能错了你改下regex试试。 或者把这个regex单独拿出来测试下。

**Comment by ShadowZheng** [comment]
@Boshen 我改后还是有问题，这是windows默认安装时候就会报这些错，帅哥你要不试试？

**Comment by Boshen** [comment]
这regex是不是少了个配对括号 
```
/^\messages\(?:([^\/]+?))\repost\/?$/
/^\messages\(?:([^\/]+?)\)\repost\/?$/
                        ^ 这里
```

**Comment by ShadowZheng** [comment]
windows下推荐一种我现在用的方案：
用docker起个容器挂载到本地工程目录，然后可以正常启动。
启动前把talk-account、talk-api2x、talk-snnaper、talk-web下的default.coffee改一下host地址。

over。
