### ISSUE TITLE
怎么开启消息搜索功能？

### ISSUE THREAD

**Issue by ShadowZheng** [jianliaoim/talk-os#24]
我按照项目主页md文件里安装环境步骤执行，到最后一步要创建索引结构直接报错，后来发现压根就没有9200端口的服务啊？

好像默认收藏和@我的消息因为用到搜索，都无法使用.
```bash
err! 2016-08-10T07:17:51.101Z POST /favorites/search [ 'host',
  'connection',
  'content-length',
  'origin',
  'x-language',
  'user-agent',
  'content-type',
  'x-socket-id',
  'accept',
  'x-requested-with',
  'referer',
  'accept-encoding',
  'accept-language',
  'cookie' ] [] [ '_teamId', 'page', 'sort' ] Error: No Living connections
  at sendReqWithConnection (/home/andy/FrontEndProjects/talk-os/talk-api2x/node_modules/elasticsearch/src/lib/transport.js:190:15)
  at next (/home/andy/FrontEndProjects/talk-os/talk-api2x/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```

@sailxjx @Boshen

**Comment by sailxjx** [comment]
部署 [es](https://www.elastic.co/)，用默认 9200 端口

**Comment by ShadowZheng** [comment]
谢谢，部署后添加ik插件了也，但是执行./create-search-template.sh 脚本报错如下
```bash
{"acknowledged":true}{"error":"IndexCreationException[[talk_favorites_v2] failed to create index]; nested: NoSuchMethodError[org.elasticsearch.env.Environment.configFile()Ljava/nio/file/Path;]; ","status":500}{"error":"IndexCreationException[[talk_stories_v2] failed to create index]; nested: NoSuchMethodError[org.elasticsearch.env.Environment.configFile()Ljava/nio/file/Path;]; ","status":500}
```
@sailxjx

**Comment by sailxjx** [comment]
ik 1.4.0

**Comment by ShadowZheng** [comment]
@sailxjx 
点击@我的消息，直接报错如下:

```bash
err! 2016-08-12T07:02:43.621Z GET /messages/mentions?_teamId=579627434dbb20a336c6e47a&limit=10 [ 'host',
  'connection',
  'x-language',
  'user-agent',
  'content-type',
  'x-socket-id',
  'accept',
  'x-requested-with',
  'referer',
  'accept-encoding',
  'accept-language',
  'cookie' ] [ '_teamId', 'limit' ] [] MongoError: Unable to execute query: error processing query: ns=talk.messages limit=10 skip=0
Tree: $and
    mentions == ObjectId('5796273d4dbb20a336c6e479')
    team == ObjectId('579627434dbb20a336c6e47a')
    room $in [ ObjectId('579627434dbb20a336c6e47b') ObjectId('5798d0dfb98146630fdcde90') ObjectId('5798d3a0b98146630fdcde94') ObjectId('5798d481b98146630fdcde98') ObjectId('5798d623b98146630fdcde9b') ObjectId('57997929aa6ab9172b7d0d06') ObjectId('57a2f258c6a70fd1344c846a') ObjectId('57a314566f8a205c497796ff') ]
Sort: { _id: -1 }
Proj: {}
 planner returned error: bad hint
  at Function.MongoError.create (/home/andy/FrontEndProjects/talk-os/talk-api2x/node_modules/mongodb-core/lib/error.js:31:11)
  at queryCallback (/home/andy/FrontEndProjects/talk-os/talk-api2x/node_modules/mongodb-core/lib/cursor.js:182:34)
  at Callbacks.emit (/home/andy/FrontEndProjects/talk-os/talk-api2x/node_modules/mongodb-core/lib/topologies/server.js:119:3)
  at .messageHandler (/home/andy/FrontEndProjects/talk-os/talk-api2x/node_modules/mongodb-core/lib/topologies/server.js:397:23)
  at Socket.<anonymous> (/home/andy/FrontEndProjects/talk-os/talk-api2x/node_modules/mongodb-core/lib/connection/connection.js:302:22)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at readableAddChunk (_stream_readable.js:177:18)
  at Socket.Readable.push (_stream_readable.js:135:10)
  at TCP.onread (net.js:542:20)

```

**Comment by ShadowZheng** [comment]
请按照 @sailxjx 说的版本进行安装，thanks
