### ISSUE TITLE
npm run init 报错

### ISSUE THREAD

**Issue by motcwang** [jianliaoim/talk-os#29]
执行到_Install packages of talk-os_的时候报错如下：
```
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/wangchao/.nvm/versions/node/v4.6.0/bin/node" "/Users/wangchao/.nvm/versions/node/v4.6.0/bin/npm" "run" "init"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! talk-os@1.0.0 init: `./init.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the talk-os@1.0.0 init script './init.sh'.
npm ERR! This is most likely a problem with the talk-os package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./init.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs talk-os
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls talk-os
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wangchao/Design/OpenSource/talk-os-master/npm-debug.log
```
下面为npm-debug.log的内容：
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/wangchao/.nvm/versions/node/v4.6.0/bin/node',
1 verbose cli   '/Users/wangchao/.nvm/versions/node/v4.6.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'init' ]
2 info using npm@2.15.9
3 info using node@v4.6.0
4 verbose run-script [ 'preinit', 'init', 'postinit' ]
5 info preinit talk-os@1.0.0
6 info init talk-os@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info talk-os@1.0.0 Failed to exec init script
9 verbose stack Error: talk-os@1.0.0 init: `./init.sh`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/Users/wangchao/.nvm/versions/node/v4.6.0/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/Users/wangchao/.nvm/versions/node/v4.6.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid talk-os@1.0.0
11 verbose cwd /Users/wangchao/Design/OpenSource/talk-os-master
12 error Darwin 15.5.0
13 error argv "/Users/wangchao/.nvm/versions/node/v4.6.0/bin/node" "/Users/wangchao/.nvm/versions/node/v4.6.0/bin/npm" "run" "init"
14 error node v4.6.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error talk-os@1.0.0 init: `./init.sh`
17 error Exit status 1
18 error Failed at the talk-os@1.0.0 init script './init.sh'.
18 error This is most likely a problem with the talk-os package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     ./init.sh
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs talk-os
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls talk-os
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by motcwang** [comment]
执行npm start    localhost:7001
```
{"code":404,"message":"Not Found"}
```

**Comment by motcwang** [comment]
刚发现，我自己的版本不对。
