### ISSUE TITLE
调用 API 失败

### ISSUE THREAD

**Issue by afc163** [jianliaoim/talk-os#8]
请求 notifications 接口时报错，信息如下：

```
info 2016-04-01T03:54:37.676Z Req GET /notifications?_teamId=56fd15c1cc323cf1c8c08f15 _teamId 
[Fri, 01 Apr 2016 03:54:37 GMT] talk_web 56fd15b9cc323cf1c8c08f14 GET /v2/notifications?_teamId=56fd15c1cc323cf1c8c08f15 _teamId Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0 200 3177 24.700 ms
info 2016-04-01T03:54:38.027Z Req GET /notifications?_teamId=56fd15c1cc323cf1c8c08f15&maxUpdatedAt=1459426754660&limit=10 _teamId,maxUpdatedAt,limit 
err! 2016-04-01T03:54:38.031Z GET /notifications?_teamId=56fd15c1cc323cf1c8c08f15&maxUpdatedAt=1459426754660&limit=10 [ 'host',
  'user-agent',
  'accept',
  'accept-language',
  'accept-encoding',
  'referer',
  'x-socket-id',
  'x-language',
  'x-requested-with',
  'content-type',
  'cookie',
  'connection',
  'pragma',
  'cache-control' ] [ '_teamId', 'maxUpdatedAt', 'limit' ] [] MongoError: Failed to parse: { find: "notifications", filter: { updatedAt: { $lt: new Date(1459426754660) }, isPinned: false, isHidden: false, team: ObjectId('56fd15c1cc323cf1c8c08f15'), user: ObjectId('56fd15b9cc323cf1c8c08f14') }, sort: { updatedAt: -1 }, limit: "10" }. 'limit' field must be numeric.
  at Function.MongoError.create (/Users/afc163/Projects/talk-os/talk-api2x/node_modules/mongodb-core/lib/error.js:31:11)
  at queryCallback (/Users/afc163/Projects/talk-os/talk-api2x/node_modules/mongodb-core/lib/cursor.js:196:36)
  at [object Object].Callbacks.emit (/Users/afc163/Projects/talk-os/talk-api2x/node_modules/mongodb-core/lib/topologies/server.js:116:3)
  at [object Object].messageHandler (/Users/afc163/Projects/talk-os/talk-api2x/node_modules/mongodb-core/lib/topologies/server.js:291:23)
  at Socket.<anonymous> (/Users/afc163/Projects/talk-os/talk-api2x/node_modules/mongodb-core/lib/connection/connection.js:285:22)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:523:20)

[Fri, 01 Apr 2016 03:54:38 GMT] talk_web 56fd15b9cc323cf1c8c08f14 GET /v2/notifications?_teamId=56fd15c1cc323cf1c8c08f15&maxUpdatedAt=1459426754660&limit=10 _teamId,maxUpdatedAt,limit Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0 500 320 5.408 ms
```

版本：https://github.com/jianliaoim/talk-os/tree/3f64918151664ddd6b35e2af56f3a2ea250945bb

**Comment by sailxjx** [comment]
@afc163 这个错误我这里无法重现，能提供一下 mongodb, mongoose, node 的版本吗

**Comment by afc163** [comment]
- MongoDB: 3.2.4
- redis: 2.8.24 
- node: 5.1.1

**Comment by niuba** [comment]
同样出现这个问题
主要在这里limit: "10"  'limit' field must be numeric
MongoDB: 3.2.4
redis: 3.0.7
node: 4.4.2

**Comment by moodpo** [comment]
我也出现同样问题了

**Comment by moodpo** [comment]
貌似很多 scheme 里的`limit`都要改啊

**Comment by sailxjx** [comment]
@moodpo 感谢反馈

我这里不能重现，现在对入口参数做了一下类型转换，应该可以避免这个问题

https://github.com/jianliaoim/talk-os/commit/51f8241535344bacac23dc570269aa6c01b1ae42
